### ISSUE TITLE
请问PrpCrypt类是根据什么来编写的？

### ISSUE THREAD

**Issue by GoTop** [musistudio/iflytek-tts#1]
是否需要先嗅探配音阁生成tts语音时提交的post包？

但是如何知道它使用的是AES加密呢？

还有，如何知道使用的密钥是什么？

**Comment by musistudio** [comment]
你分析一下配音阁的js代码应该就知道了

**Comment by GoTop** [comment]
> 你分析一下配音阁的js代码应该就知道了

恩，多谢了~
